### ISSUE TITLE
Bluetooth realtime signal on Matlab 

### ISSUE THREAD

**Issue by Haris522** [dengcai78/MatlabFunc#6]
Hello, I'm working on a Home automation using Arduino and Bluetooth module (HC-05). 
My project is to control electric appliances through Bluetooth and filter the realtime Bluetooth signal on matlab.
Can anyone tell me how can i get real-time signal on matlab?

Want Arduino and Matlab complete code.

Thanks.

**Comment by zhaojiaoyan** [comment]
您好，我是赵娇燕，您的邮件已收到，我会尽快回复给您的！
